[tox]
minversion = 1.6
envlist = docs,docs-linkcheck
skipsdist = true

[testenv:docs]
basepython = python3.13
deps =
    -r{toxinidir}/requirements-docs.txt
    -c{toxinidir}/../etc/upper-constraints.onap.txt
commands =
    sphinx-build -W -q -b html -n -d {envtmpdir}/doctrees {toxinidir} {toxinidir}/_build/html
allowlist_externals =
    git
    sh

[testenv:docs-linkcheck]
basepython = python3.13
deps =
    -r{toxinidir}/requirements-docs.txt
    -c{toxinidir}/../etc/upper-constraints.onap.txt
commands = sphinx-build -W -q -b linkcheck -d {envtmpdir}/doctrees {toxinidir} {toxinidir}/_build/linkcheck
